import { createFileRoute } from '@tanstack/react-router';
import { extractTranslation } from '@/lib/extractTranslation.tsx';
import {
  Carousel,
  CarouselContent,
  CarouselItem,
  CarouselNext,
  CarouselPrevious,
} from '@/components/ui/carousel';
import { useEffect, useState } from 'react';
import {
  Card,
  CardAction,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from '@/components/ui/card.tsx';
import { Button } from '@/components/ui/button.tsx';

export const Route = createFileRoute('/schedule')({
  component: Schedule,
  staticData: {
    titleData: extractTranslation('Pages.Schedule.navbarTitle', 'Schedule'),
    hideInNav: true,
    order: -1,
  },
});

// 1. Updated interface to match the numbers generated by getTime() and getDate()
interface EventType {
  id: string;
  title: string;
  description: string;
  start: number;
  end: number;
}

export function Schedule() {
  // 2. Added <EventType[]> to type the state correctly
  const [events, setEvents] = useState<EventType[]>([]);

  useEffect(() => {
    fetch(
      'https://script.google.com/macros/s/AKfycbyhzEfK6fvtSwrbSPLH6NESjAcXmabHVAwLchqNNg9ulkQPDUzOu73L8aT-VBTXbjRY7g/exec'
    )
      .then((res) => res.json())
      .then((data: EventType[]) =>
        setEvents(
          // 3. Added 'item' to map over individual objects instead of the main 'data' array
          data.map((item) => ({
            id: item.id,
            title: item.title,
            description: item.description,
            start: new Date(item.start).getTime(),
            end: new Date(item.end).getTime(),
          }))
        )
      )
      .catch((err) => console.error(err));
  }, []);

  return (
    <div className="bg-background flex min-h-screen w-full items-center justify-center">
      <Carousel
        className="w-full max-w-xl"
        opts={{
          align: 'start', // Aligns the first item to the start of the container
        }}
      >
        <CarouselContent>
          {events.map((event: EventType) => (
            <CarouselItem key={event.id} className="basis-[85%] sm:basis-[80%]">
              <Card className="h-full flex flex-col">
                <CardHeader>
                  <CardTitle>{event.title}</CardTitle>
                  <CardAction>
                    <Button variant={'ghost'}>Przypominaj o spotkaniach</Button>
                  </CardAction>
                </CardHeader>
                <CardContent className="space-y-4 grow">
                  <CardDescription>{event.description}</CardDescription>
                  <div className="text-sm font-medium">
                    <p>
                      When: {new Date(event.start).toLocaleTimeString()}{' '}
                      {new Date(event.start).toLocaleDateString()}
                    </p>
                    <p>Till: {new Date(event.end).toLocaleTimeString()}</p>
                  </div>
                </CardContent>
                <CardFooter className={'flex justify-between *:mx-2 *:grow'}>
                  <Button variant={'default'}>Wbijam!!</Button>
                </CardFooter>
              </Card>
            </CarouselItem>
          ))}
        </CarouselContent>
        <CarouselPrevious className="hidden sm:flex" />
        <CarouselNext className="hidden sm:flex" />
      </Carousel>
    </div>
  );
}
