import { createFileRoute } from '@tanstack/react-router';
import { extractTranslation } from '@/lib/extractTranslation.tsx';
import {
  Carousel,
  CarouselContent,
  CarouselItem,
  CarouselNext,
  CarouselPrevious,
} from '@/components/ui/carousel';
import {
  Card,
  CardAction,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from '@/components/ui/card.tsx';
import { Button } from '@/components/ui/button.tsx';
import { Badge } from '@/components/ui/badge.tsx';
import { RiCalendar2Line } from '@remixicon/react';
import { sections } from '@/routes/sections.tsx';
import { useTranslation } from 'react-i18next';
import { Skeleton } from '@/components/ui/skeleton.tsx';
import { useCalendarLinks } from '@/lib/useCalendarLinks.tsx';
import { useQuery } from '@tanstack/react-query';

export const Route = createFileRoute('/schedule')({
  component: Schedule,
  staticData: {
    titleData: extractTranslation('Pages.Schedule.navbarTitle', 'Schedule'),
    hideInNav: false,
    order: 3,
  },
});

// 1. Updated interface to match the numbers generated by getTime() and getDate()
interface EventType {
  id: string;
  title: string;
  description: string;
  start: Date;
  end: Date;
  calendarName: string;
  eventLinks: {
    googleTemplateUrl: string;
    icsUrl: string;
    googleSubscribeUrl: string;
    webcalUrl: string;
  };
}

const fetchCalendarEvents = async () => {
  // We still keep the cache buster because Google Apps Script is notoriously sticky
  const scriptUrl =
    'https://script.google.com/macros/s/AKfycbx6k6b3VQW02WpwBeQiaK4KYNmeR-BJ4Zo8VnwXYeqdGgj0rviGbdY1sa7cXPFc45A8Qw/exec';
  const res = await fetch(`${scriptUrl}`);

  if (!res.ok) throw new Error('Failed to fetch events');

  const data = await res.json();

  return data.map((item: EventType) => ({
    calendarName: item.calendarName,
    id: item.id,
    title: item.title,
    description: item.description,
    start: new Date(item.start),
    end: new Date(item.end),
    eventLinks: item.eventLinks,
  }));
};

export function Schedule() {
  const { t } = useTranslation();

  return (
    <div className="bg-background flex py-10 w-full items-center justify-center flex-col space-y-4">
      <Badge variant="secondary" className="px-3 py-1 text-sm font-medium">
        <RiCalendar2Line className="mr-2 h-4 w-4" />
        {t('Pages.Schedule.badge', 'Harmonogram spotkań')}
      </Badge>
      <h2 className="text-3xl font-bold tracking-tight md:text-4xl">
        {t('Pages.Schedule.title', 'Kiedy się spotykamy?')}
      </h2>
      <p className="max-w-2xl text-lg text-muted-foreground text-balance">
        {t(
          'Pages.Schedule.paragraph',
          'Lista zaplanowanych spotkań na kolejny miesiąc'
        )}
      </p>
      {/* Suspense removed. The child component handles its own loading state */}
      <LoadedCarousel />
    </div>
  );
}

function LoadedCarousel() {
  const { t } = useTranslation();
  const {
    data: events = [],
    isLoading,
    isError,
  } = useQuery({
    queryKey: ['calendarEvents'], // A unique key for this data
    queryFn: fetchCalendarEvents,
    staleTime: 1000 * 60 * 5, // Data is fresh for 5 minutes (won't refetch on tab switch)
  });

  // 3. Show Skeleton if fetching
  if (isLoading) {
    return <GhostCarousel />;
  }

  // 4. Show Empty State if no events
  if (events.length === 0 || isError) {
    return (
      <Card>
        <CardHeader>
          {/* Removed wrapping <h2> to fix hydration error */}
          <CardTitle>
            {t('Pages.Schedule.notFound.title', 'O kurcze!!')}
          </CardTitle>
        </CardHeader>
        <CardContent>
          {/* Removed wrapping <p> to fix hydration error */}
          <CardDescription className="max-w-2xl text-lg text-muted-foreground text-balance">
            {t(
              'Pages.Schedule.notFound.paragraph',
              'Nie mamy zaplanowanych żadnych spotkań, możliwe że w kolejnych dniach to się zmieni.'
            )}
          </CardDescription>
        </CardContent>
      </Card>
    );
  }

  // 5. Show Actual Data
  return (
    <Carousel
      className="w-full max-w-9/11" // Changed from invalid 9/11
      opts={{ align: 'center' }}
    >
      <CarouselContent>
        {events.map((event: EventType) => {
          const matchedSection = sections.find((section) =>
            event.calendarName
              .toLowerCase()
              .includes(section.title.toLowerCase())
          );
          return (
            <EventCarouselItem
              key={`${event.id}-${event.calendarName}-${event.start}`}
              event={event}
              matchedSection={matchedSection}
            />
          );
        })}
      </CarouselContent>
      <CarouselPrevious className="hidden sm:flex" />
      <CarouselNext className="hidden sm:flex" />
    </Carousel>
  );
}

function EventCarouselItem({
  event,
  matchedSection,
}: {
  event: EventType;
  matchedSection: (typeof sections)[0] | undefined;
}) {
  // ✅ The hook is now safely at the top level of a component
  // Note: Pass event.eventLinks if you used the Apps Script structure from earlier
  const { singularLink, entireLink } = useCalendarLinks(event.eventLinks);
  const Icon = matchedSection?.icon;

  return (
    <CarouselItem className="md:basis-[27dvw] basis-1/3">
      <Card className="h-full flex flex-col group bg-muted/50 shadow-sm transition-shadow duration-300 hover:shadow-md dark:hover:bg-muted/70">
        {matchedSection && (
          <Badge
            variant="secondary"
            className="px-3 py-1 text-sm font-medium flex items-center mx-7"
          >
            {Icon && <Icon className="mr-2 h-4 w-4" />}
            {matchedSection.title}
          </Badge>
        )}
        <CardHeader>
          <CardTitle className="flex text-xl group-hover:text-blue-600 dark:group-hover:text-blue-400 transition-colors duration-300">
            {event.title}
          </CardTitle>
          <CardAction>
            {/* Example of using the entireLink */}
            <Button variant="ghost">
              <a href={entireLink} target="_blank" rel="noreferrer">
                Przypominaj o spotkaniach (Subskrybuj)
              </a>
            </Button>
          </CardAction>
        </CardHeader>
        <CardContent className="space-y-4 grow">
          <CardDescription>{event.description}</CardDescription>
          <div className="text-sm font-medium">
            <p>{`${event.start.toLocaleTimeString()} - ${event.end.toLocaleTimeString()}`}</p>
            <p>{event.start.toLocaleDateString()}</p>
          </div>
        </CardContent>
        <CardFooter className="flex justify-between *:mx-2 *:grow">
          {/* Example of using the singularLink */}
          <Button variant="default">
            <a href={singularLink} target="_blank" rel="noreferrer">
              Wbijam!! (Zapisz to wydarzenie)
            </a>
          </Button>
        </CardFooter>
      </Card>
    </CarouselItem>
  );
}
// 6. The Skeleton Component using Shadcn <Skeleton />
function GhostCarousel() {
  return (
    <Carousel className="w-full max-w-[80%]" opts={{ align: 'center' }}>
      <CarouselContent>
        {/* Render 4 dummy skeleton cards so the carousel looks full */}
        {Array.from({ length: 4 }).map((_, index) => (
          <CarouselItem key={index} className="md:basis-[27dvw] basis-1/3">
            <Card className="h-full flex flex-col">
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Skeleton className="h-6 w-20 rounded-full" />{' '}
                  {/* Badge skeleton */}
                  <Skeleton className="h-6 w-32" /> {/* Title skeleton */}
                </CardTitle>
                <CardAction>
                  <Skeleton className="h-9 w-full rounded-md" />{' '}
                  {/* Button skeleton */}
                </CardAction>
              </CardHeader>
              <CardContent className="space-y-4 grow flex flex-col justify-between">
                <Skeleton className="h-16 w-full" />{' '}
                {/* Description skeleton */}
                <div className="space-y-2 mt-auto">
                  <Skeleton className="h-4 w-24" /> {/* Time skeleton */}
                  <Skeleton className="h-4 w-20" /> {/* Date skeleton */}
                </div>
              </CardContent>
              <CardFooter className="flex justify-between *:mx-2 *:grow">
                <Skeleton className="h-10 w-full rounded-md" />{' '}
                {/* Main Action Button skeleton */}
              </CardFooter>
            </Card>
          </CarouselItem>
        ))}
      </CarouselContent>
      <CarouselPrevious className="hidden sm:flex" />
      <CarouselNext className="hidden sm:flex" />
    </Carousel>
  );
}
