import { createFileRoute } from '@tanstack/react-router';
import { extractTranslation } from '@/lib/extractTranslation.tsx';
import {
  Carousel,
  CarouselContent,
  CarouselItem,
  CarouselNext,
  CarouselPrevious,
} from '@/components/ui/carousel';
import { useEffect, useState } from 'react';
import {
  Card,
  CardAction,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from '@/components/ui/card.tsx';
import { Button } from '@/components/ui/button.tsx';
import { Badge } from '@/components/ui/badge.tsx';
import { RiCalendar2Line } from '@remixicon/react';
import { sections } from '@/routes/sections.tsx';
import { useTranslation } from 'react-i18next';
import { Skeleton } from '@/components/ui/skeleton.tsx';

export const Route = createFileRoute('/schedule')({
  component: Schedule,
  staticData: {
    titleData: extractTranslation('Pages.Schedule.navbarTitle', 'Schedule'),
    hideInNav: true,
    order: -1,
  },
});

// 1. Updated interface to match the numbers generated by getTime() and getDate()
interface EventType {
  id: string;
  title: string;
  description: string;
  start: Date;
  end: Date;
  calendarName: string;
}

export function Schedule() {
  const { t } = useTranslation();

  return (
    <div className="bg-background flex py-10 w-full items-center justify-center flex-col space-y-4">
      <Badge variant="secondary" className="px-3 py-1 text-sm font-medium">
        <RiCalendar2Line className="mr-2 h-4 w-4" />
        {t('Pages.Schedule.badge', 'Harmonogram spotkań')}
      </Badge>
      <h2 className="text-3xl font-bold tracking-tight md:text-4xl">
        {t('Pages.Schedule.title', 'Kiedy się spotykamy?')}
      </h2>
      <p className="max-w-2xl text-lg text-muted-foreground text-balance">
        {t(
          'Pages.Schedule.paragraph',
          'Lista zaplanowanych spotkań na kolejny miesiąc'
        )}
      </p>
      {/* Suspense removed. The child component handles its own loading state */}
      <LoadedCarousel />
    </div>
  );
}

function LoadedCarousel() {
  const { t } = useTranslation();
  const [events, setEvents] = useState<EventType[]>([]);
  const [isLoading, setIsLoading] = useState(true); // 1. Added loading state

  useEffect(() => {
    fetch(
      'https://script.google.com/macros/s/AKfycbyUGIAWurd7931vh3zLLMvvyWJhxrtNCDW5OT0GQS2f-haIZGfMZFUSfKD6Ax85wsdtSQ/exec'
    )
      .then((res) => res.json())
      .then((data: EventType[]) => {
        setEvents(
          data.map((item) => ({
            calendarName: item.calendarName,
            id: item.id,
            title: item.title,
            description: item.description,
            start: new Date(item.start),
            end: new Date(item.end),
          }))
        );
      })
      .catch((err) => console.error(err))
      .finally(() => setIsLoading(false)); // 2. Turn off loading when done
  }, []);

  // 3. Show Skeleton if fetching
  if (isLoading) {
    return <GhostCarousel />;
  }

  // 4. Show Empty State if no events
  if (events.length === 0) {
    return (
      <Card>
        <CardHeader>
          {/* Removed wrapping <h2> to fix hydration error */}
          <CardTitle>
            {t('Pages.Schedule.notFound.title', 'O kurcze!!')}
          </CardTitle>
        </CardHeader>
        <CardContent>
          {/* Removed wrapping <p> to fix hydration error */}
          <CardDescription className="max-w-2xl text-lg text-muted-foreground text-balance">
            {t(
              'Pages.Schedule.notFound.paragraph',
              'Nie mamy zaplanowanych żadnych spotkań, możliwe że w kolejnych dniach to się zmieni.'
            )}
          </CardDescription>
        </CardContent>
      </Card>
    );
  }

  // 5. Show Actual Data
  return (
    <Carousel
      className="w-full max-w-[80%]" // Changed from invalid 9/11
      opts={{ align: 'center' }}
    >
      <CarouselContent>
        {events.map((event: EventType) => {
          const matchedSection = sections.find((section) =>
            event.calendarName
              .toLowerCase()
              .includes(section.title.toLowerCase())
          );
          const Icon = matchedSection?.icon;

          return (
            <CarouselItem
              key={event.id} // Changed to id for uniqueness
              className="md:basis-[27dvw] basis-1/3"
            >
              <Card className="h-full flex flex-col group bg-muted/50 shadow-sm transition-shadow duration-300 hover:shadow-md dark:hover:bg-muted/70">
                {matchedSection && (
                  <Badge
                    variant="secondary"
                    className="px-3 py-1 text-sm font-medium flex items-center mx-7"
                  >
                    {Icon && <Icon className="mr-2 h-4 w-4" />}
                    {matchedSection.title}
                  </Badge>
                )}
                <CardHeader>
                  <CardTitle className="flex text-xl group-hover:text-blue-600 dark:group-hover:text-blue-400 transition-colors duration-300">
                    {event.title}
                  </CardTitle>
                  <CardAction>
                    <Button variant="ghost">Przypominaj o spotkaniach</Button>
                  </CardAction>
                </CardHeader>
                <CardContent className="space-y-4 grow">
                  <CardDescription>{event.description}</CardDescription>
                  <div className="text-sm font-medium">
                    <p>{`${event.start.toLocaleTimeString()} - ${event.end.toLocaleTimeString()}`}</p>
                    <p>{event.start.toLocaleDateString()}</p>
                  </div>
                </CardContent>
                <CardFooter className="flex justify-between *:mx-2 *:grow">
                  <Button
                    variant="default"
                    onClick={() => console.log(event.title.split(' ').pop())}
                  >
                    Wbijam!!
                  </Button>
                </CardFooter>
              </Card>
            </CarouselItem>
          );
        })}
      </CarouselContent>
      <CarouselPrevious className="hidden sm:flex" />
      <CarouselNext className="hidden sm:flex" />
    </Carousel>
  );
}

// 6. The Skeleton Component using Shadcn <Skeleton />
function GhostCarousel() {
  return (
    <Carousel className="w-full max-w-[80%]" opts={{ align: 'center' }}>
      <CarouselContent>
        {/* Render 4 dummy skeleton cards so the carousel looks full */}
        {Array.from({ length: 4 }).map((_, index) => (
          <CarouselItem key={index} className="md:basis-[27dvw] basis-1/3">
            <Card className="h-full flex flex-col">
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Skeleton className="h-6 w-20 rounded-full" />{' '}
                  {/* Badge skeleton */}
                  <Skeleton className="h-6 w-32" /> {/* Title skeleton */}
                </CardTitle>
                <CardAction>
                  <Skeleton className="h-9 w-full rounded-md" />{' '}
                  {/* Button skeleton */}
                </CardAction>
              </CardHeader>
              <CardContent className="space-y-4 grow flex flex-col justify-between">
                <Skeleton className="h-16 w-full" />{' '}
                {/* Description skeleton */}
                <div className="space-y-2 mt-auto">
                  <Skeleton className="h-4 w-24" /> {/* Time skeleton */}
                  <Skeleton className="h-4 w-20" /> {/* Date skeleton */}
                </div>
              </CardContent>
              <CardFooter className="flex justify-between *:mx-2 *:grow">
                <Skeleton className="h-10 w-full rounded-md" />{' '}
                {/* Main Action Button skeleton */}
              </CardFooter>
            </Card>
          </CarouselItem>
        ))}
      </CarouselContent>
      <CarouselPrevious className="hidden sm:flex" />
      <CarouselNext className="hidden sm:flex" />
    </Carousel>
  );
}
