/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as SectionsRouteImport } from './routes/sections'
import { Route as ProjectsAquasharpRouteImport } from './routes/projects/aquasharp'
import { Route as ProjectsCodewarehouseRouteImport } from './routes/projects/codewarehouse'
import { Route as ProjectsVetlinkRouteImport } from './routes/projects/vetlink'
import { Route as SectionsCybersecRouteImport } from './routes/sections/cybersec'
import { Route as SectionsDataChar38aiRouteImport } from './routes/sections/data&ai'
import { Route as SectionsWebdevRouteImport } from './routes/sections/webdev'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionsRoute = SectionsRouteImport.update({
  id: '/sections',
  path: '/sections',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsAquasharpRoute = ProjectsAquasharpRouteImport.update({
  id: '/aquasharp',
  path: '/aquasharp',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsCodewarehouseRoute = ProjectsCodewarehouseRouteImport.update({
  id: '/codewarehouse',
  path: '/codewarehouse',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsVetlinkRoute = ProjectsVetlinkRouteImport.update({
  id: '/vetlink',
  path: '/vetlink',
  getParentRoute: () => ProjectsRoute,
} as any)
const SectionsCybersecRoute = SectionsCybersecRouteImport.update({
  id: '/cybersec',
  path: '/cybersec',
  getParentRoute: () => SectionsRoute,
} as any)
const SectionsDataChar38aiRoute = SectionsDataChar38aiRouteImport.update({
  id: '/data&ai',
  path: '/data&ai',
  getParentRoute: () => SectionsRoute,
} as any)
const SectionsWebdevRoute = SectionsWebdevRouteImport.update({
  id: '/webdev',
  path: '/webdev',
  getParentRoute: () => SectionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/partners': typeof PartnersRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/sections': typeof SectionsRouteWithChildren
  '/projects/aquasharp': typeof ProjectsAquasharpRoute
  '/projects/codewarehouse': typeof ProjectsCodewarehouseRoute
  '/projects/vetlink': typeof ProjectsVetlinkRoute
  '/sections/cybersec': typeof SectionsCybersecRoute
  '/sections/data&ai': typeof SectionsDataChar38aiRoute
  '/sections/webdev': typeof SectionsWebdevRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/partners': typeof PartnersRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/sections': typeof SectionsRouteWithChildren
  '/projects/aquasharp': typeof ProjectsAquasharpRoute
  '/projects/codewarehouse': typeof ProjectsCodewarehouseRoute
  '/projects/vetlink': typeof ProjectsVetlinkRoute
  '/sections/cybersec': typeof SectionsCybersecRoute
  '/sections/data&ai': typeof SectionsDataChar38aiRoute
  '/sections/webdev': typeof SectionsWebdevRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/partners': typeof PartnersRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/sections': typeof SectionsRouteWithChildren
  '/projects/aquasharp': typeof ProjectsAquasharpRoute
  '/projects/codewarehouse': typeof ProjectsCodewarehouseRoute
  '/projects/vetlink': typeof ProjectsVetlinkRoute
  '/sections/cybersec': typeof SectionsCybersecRoute
  '/sections/data&ai': typeof SectionsDataChar38aiRoute
  '/sections/webdev': typeof SectionsWebdevRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/partners'
    | '/projects'
    | '/sections'
    | '/projects/aquasharp'
    | '/projects/codewarehouse'
    | '/projects/vetlink'
    | '/sections/cybersec'
    | '/sections/data&ai'
    | '/sections/webdev'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/partners'
    | '/projects'
    | '/sections'
    | '/projects/aquasharp'
    | '/projects/codewarehouse'
    | '/projects/vetlink'
    | '/sections/cybersec'
    | '/sections/data&ai'
    | '/sections/webdev'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/partners'
    | '/projects'
    | '/sections'
    | '/projects/aquasharp'
    | '/projects/codewarehouse'
    | '/projects/vetlink'
    | '/sections/cybersec'
    | '/sections/data&ai'
    | '/sections/webdev'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PartnersRoute: typeof PartnersRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  SectionsRoute: typeof SectionsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sections': {
      id: '/sections'
      path: '/sections'
      fullPath: '/sections'
      preLoaderRoute: typeof SectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/aquasharp': {
      id: '/projects/aquasharp'
      path: '/aquasharp'
      fullPath: '/projects/aquasharp'
      preLoaderRoute: typeof ProjectsAquasharpRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/codewarehouse': {
      id: '/projects/codewarehouse'
      path: '/codewarehouse'
      fullPath: '/projects/codewarehouse'
      preLoaderRoute: typeof ProjectsCodewarehouseRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/vetlink': {
      id: '/projects/vetlink'
      path: '/vetlink'
      fullPath: '/projects/vetlink'
      preLoaderRoute: typeof ProjectsVetlinkRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/sections/cybersec': {
      id: '/sections/cybersec'
      path: '/cybersec'
      fullPath: '/sections/cybersec'
      preLoaderRoute: typeof SectionsCybersecRouteImport
      parentRoute: typeof SectionsRoute
    }
    '/sections/data&ai': {
      id: '/sections/data&ai'
      path: '/data&ai'
      fullPath: '/sections/data&ai'
      preLoaderRoute: typeof SectionsDataChar38aiRouteImport
      parentRoute: typeof SectionsRoute
    }
    '/sections/webdev': {
      id: '/sections/webdev'
      path: '/webdev'
      fullPath: '/sections/webdev'
      preLoaderRoute: typeof SectionsWebdevRouteImport
      parentRoute: typeof SectionsRoute
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsAquasharpRoute: typeof ProjectsAquasharpRoute
  ProjectsCodewarehouseRoute: typeof ProjectsCodewarehouseRoute
  ProjectsVetlinkRoute: typeof ProjectsVetlinkRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsAquasharpRoute: ProjectsAquasharpRoute,
  ProjectsCodewarehouseRoute: ProjectsCodewarehouseRoute,
  ProjectsVetlinkRoute: ProjectsVetlinkRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface SectionsRouteChildren {
  SectionsCybersecRoute: typeof SectionsCybersecRoute
  SectionsDataChar38aiRoute: typeof SectionsDataChar38aiRoute
  SectionsWebdevRoute: typeof SectionsWebdevRoute
}

const SectionsRouteChildren: SectionsRouteChildren = {
  SectionsCybersecRoute: SectionsCybersecRoute,
  SectionsDataChar38aiRoute: SectionsDataChar38aiRoute,
  SectionsWebdevRoute: SectionsWebdevRoute,
}

const SectionsRouteWithChildren = SectionsRoute._addFileChildren(
  SectionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PartnersRoute: PartnersRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  SectionsRoute: SectionsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
