/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as SectionsRouteImport } from './routes/sections'
import { Route as SectionsWebdevRouteImport } from './routes/sections/Webdev'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionsRoute = SectionsRouteImport.update({
  id: '/sections',
  path: '/sections',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionsWebdevRoute = SectionsWebdevRouteImport.update({
  id: '/Webdev',
  path: '/Webdev',
  getParentRoute: () => SectionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/schedule': typeof ScheduleRoute
  '/sections': typeof SectionsRouteWithChildren
  '/sections/Webdev': typeof SectionsWebdevRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/schedule': typeof ScheduleRoute
  '/sections': typeof SectionsRouteWithChildren
  '/sections/Webdev': typeof SectionsWebdevRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/schedule': typeof ScheduleRoute
  '/sections': typeof SectionsRouteWithChildren
  '/sections/Webdev': typeof SectionsWebdevRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/schedule' | '/sections' | '/sections/Webdev'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/schedule' | '/sections' | '/sections/Webdev'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/schedule'
    | '/sections'
    | '/sections/Webdev'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ScheduleRoute: typeof ScheduleRoute
  SectionsRoute: typeof SectionsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sections': {
      id: '/sections'
      path: '/sections'
      fullPath: '/sections'
      preLoaderRoute: typeof SectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sections/Webdev': {
      id: '/sections/Webdev'
      path: '/Webdev'
      fullPath: '/sections/Webdev'
      preLoaderRoute: typeof SectionsWebdevRouteImport
      parentRoute: typeof SectionsRoute
    }
  }
}

interface SectionsRouteChildren {
  SectionsWebdevRoute: typeof SectionsWebdevRoute
}

const SectionsRouteChildren: SectionsRouteChildren = {
  SectionsWebdevRoute: SectionsWebdevRoute,
}

const SectionsRouteWithChildren = SectionsRoute._addFileChildren(
  SectionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ScheduleRoute: ScheduleRoute,
  SectionsRoute: SectionsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
